name = "lucia-secure"
main = "src/worker.mjs"
compatibility_date = "2024-11-20"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[vars]
# Optional defaults (you can override in dashboard)
OPENAI_MODEL = "gpt-4o-mini"
ALLOW_ORIGIN = "*"
OPENAI_PROXY_URL = "https://acmjtgoc47eieiii6gksw3bx6u0feemy.lambda-url.eu-west-1.on.aws/"